POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZSIsImlkIjoiNjNmMzU4NmY0ZThhNDEyODA5NDM4OTU5IiwiaWF0IjoxNjc2OTAwNjUzfQ.KXX7Lhx5C-hLmOTCoh0DkUf0pu3ZLjMIAyz_Mv1n9Es


{
  "title": "This will be deleted",
  "author": "Ya Heards",
  "url": "23",
  "likes": 1,
  "userId": "63f34d2e216df0f38d5ee1a9"
}